const os = require('os')
//console.log(os.cpus())
console.log(os.homedir())
console.log(os.hostname())
console.log(os.release())

console.log(os.uptime())
console.log(os.version())
console.log(os.type())
console.log(os.tmpdir())
console.log(os.platform())
console.log(os.loadavg())
console.log(os.endianness())
console.log(os.constants)